### Registrar um Tutor
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "cpf": "12345678902",
  "nome": "Joao Silva",
  "email": "joao@example.com",
  "senha": "senha123"
}


### Login de Tutor
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "pedro@example.com",
  "senha": "senha123"
}

### Listar Todos os Tutores
GET http://localhost:3000/tutors
Authorization: Bearer <Your_Token_Here>

### Obter um Tutor por ID
GET http://localhost:3000/tutors/7
Authorization: Bearer <Your_Token_Here>

### Atualizar um Tutor
PUT http://localhost:3000/tutors/7
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
  "email": "updated_joao@example.com",
  "senha": "nova_senha123"
}

### Deletar um Tutor
DELETE http://localhost:3000/tutors/7
Authorization: Bearer <Your_Token_Here>

### Registrar um Pet
POST http://localhost:3000/pets
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
  "codigo_pet": "PET123",
  "nome_pet": "Rex",
  "genero_pet": "Masculino",
  "altura_valor": 20.0,
  "tutorId": 9
}

### Listar Todos os Pets
GET http://localhost:3000/pets
Authorization: Bearer <Your_Token_Here>

### Obter um Pet por ID
GET http://localhost:3000/pets/1
Authorization: Bearer <Your_Token_Here>

### Atualizar um Pet
PUT http://localhost:3000/pets/1
Content-Type: application/json
Authorization: Bearer <Your_Token_Here>

{
  "codigo_pet": "PET123",
  "nome_pet": "Rex Updated",
  "genero_pet": "Masculino",
  "altura_valor": 25.0,
  "tutorId": 9
}

### Deletar um Pet
DELETE http://localhost:3000/pets/1
Authorization: Bearer <Your_Token_Here>

### Consultar Pets por Tutor
GET http://localhost:3000/tutors/1/pets
Authorization: Bearer <Your_Token_Here>

### Consultar Pets por Altura
GET http://localhost:3000/altura/2/pets
Authorization: Bearer <Your_Token_Here>
